import json
import re
from fpdf import FPDF
import io

def clean_text(text):
    if not isinstance(text, str):
        text = str(text)
    replacements = {
        '–': '-',
        '—': '-',
        '“': '"',
        '”': '"',
        '‘': "'",
        '’': "'",
        '…': '...',
        '•': '-',
        '₹': 'Rs ',
        '€': 'EUR ',
        '£': 'GBP ',
        '¥': 'JPY '
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    import textwrap
    text = textwrap.fill(text, width=95, replace_whitespace=False, break_long_words=True)
    return text.encode('latin-1', 'replace').decode('latin-1')

def parse_json_from_llm(text):
    """
    Safely parses JSON from the LLM output, handling markdown wrapping 
    or unexpected characters.
    """
    try:
        # Try direct parsing first
        return json.loads(text)
    except json.JSONDecodeError:
        # Try to find a JSON block in the text
        match = re.search(r'```(?:json)?\s*(.*?)\s*```', text, re.DOTALL | re.IGNORECASE)
        if match:
            try:
                return json.loads(match.group(1))
            except json.JSONDecodeError:
                pass
        
        # Try to find something that looks like an object
        match = re.search(r'({.*})', text, re.DOTALL)
        if match:
            try:
                return json.loads(match.group(1))
            except json.JSONDecodeError:
                pass
                
        # If all fails, return a default structured error object
        return {
            "error": "Failed to parse LLM output as JSON.",
            "raw_text": text
        }

def generate_pdf_report(data, currency, inputs):
    """
    Generates a PDF report from the analysis data.
    """
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Title
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 10, "FinWise AI Financial Report", ln=True, align='C')
    pdf.ln(5)
    
    # Disclaimer
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(0, 5, "Disclaimer: This report is generated by an AI for educational purposes only. It is not financial advice.")
    pdf.ln(5)
    
    currency = clean_text(currency)
    
    # User Inputs
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Financial Overview", ln=True)
    pdf.set_font("Helvetica", "", 12)
    
    pdf.cell(50, 8, "Monthly Income:", 0, 0)
    pdf.cell(0, 8, f"{currency}{inputs['monthly_income']}", 0, 1)
    
    pdf.cell(50, 8, "Total Expenses:", 0, 0)
    pdf.cell(0, 8, f"{currency}{inputs['total_expenses']}", 0, 1)
    
    pdf.cell(50, 8, "Remaining Balance:", 0, 0)
    pdf.cell(0, 8, f"{currency}{inputs['remaining_income']}", 0, 1)
    
    pdf.cell(50, 8, "Monthly Savings:", 0, 0)
    pdf.cell(0, 8, f"{currency}{inputs['savings']}", 0, 1)
    
    pdf.ln(5)
    
    if "error" in data:
        pdf.set_font("Helvetica", "B", 12)
        pdf.multi_cell(0, 10, "Error generating report data.")
        return pdf.output(dest='S').encode('latin1')

    # AI Analysis
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "AI Analysis", ln=True)
    
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, clean_text(f"Health Score: {data.get('financial_health_score', 'N/A')} / 100"), ln=True)
    pdf.cell(0, 8, clean_text(f"Risk Level: {data.get('risk_level', 'N/A')}"), ln=True)
    pdf.ln(5)
    
    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 6, clean_text(str(data.get('financial_summary', ''))))
    pdf.ln(5)
    
    # Priorities
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Top Priorities", ln=True)
    pdf.set_font("Helvetica", "", 11)
    for p in data.get('top_priorities', []):
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(0, 6, clean_text(f"- {p}"))
    pdf.ln(5)
    
    # Budget Recommendations
    if 'budget_recommendations' in data:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Budget Recommendations", ln=True)
        pdf.set_font("Helvetica", "", 11)
        for p in data.get('budget_recommendations', []):
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 6, clean_text(f"- {p}"))
        pdf.ln(5)
        
    # Savings Strategy
    if 'savings_strategy' in data:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Savings Strategy", ln=True)
        pdf.set_font("Helvetica", "", 11)
        for p in data.get('savings_strategy', []):
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 6, clean_text(f"- {p}"))
        pdf.ln(5)
    
    # Action Plan
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Next Month Action Plan", ln=True)
    pdf.set_font("Helvetica", "", 11)
    for p in data.get('next_month_action_plan', []):
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(0, 6, clean_text(f"- {p}"))
        
    # Return as bytes
    # pdf.output returns bytearray in fpdf2 if dest='S'
    return bytes(pdf.output(dest='S'))
